### ISSUE TITLE
RT is not discoverable in media picker

### ISSUE THREAD

**Issue by ebndulue** [mediacloud/web-tools#2001]
The prominent Russian sources RT (https://sources.mediacloud.org/#/sources/305385) cannot be found using the Media Picker, as searching RT/ Russia Today/ the URL each do not surface results. Only can be found by listing all Russian sources and picking from the list.

**Comment by dsjen** [comment]
I can confirm this:

<img width="733" alt="Screen Shot 2020-10-26 at 4 51 23 PM" src="https://user-images.githubusercontent.com/5265058/97227195-84375f80-17ab-11eb-8fe6-6c8c1f1d4364.png">

I suspect this has something to do with min characters for search--need to confirm that.

**Comment by hroberts** [comment]
the problem is that the media search in the api uses the very simple
approach of just searching for any medium with a name that includes the
lower cased text.  so for the search [new york times] the sql query is
literally just [select * from media where name like '%new york times%'].
to avoid returning meaninglessly long lists of results, we only do the
search with searches of at least 3 letters.  I can change that limit to
allow search of only 2 letters, but that won't help in this case because
there are 93,120 media sources in our database with the letters 'rt'.  the
solution is to improve this code to do word base searches, but that's a
non-trivial change, not so much because of the database but just because it
will change search results for users.  maybe I should add this more robust
searching as an option to the api, and y'all can test it out to make sure
it won't break things?

-hal

**Comment by dsjen** [comment]
Thanks for the explanation! I guess part of me wonders if addressing this case is worth the effort involved. Is there a way to look at how many sources are a two character name? If RT is just one of a handful, then I've vote to move on.

**Comment by hroberts** [comment]
I just added the fts index to postgres and played around with the query
options, and I think I can change it in a way that won't require user
testing and will be much faster (instant instead of ~5 seconds for a media
search).

-hal

**Comment by dsjen** [comment]
Oh, wow! That's a win win!

**Comment by hroberts** [comment]
this is implemented in the api:

https://github.com/mediacloud/backend/issues/737

**Comment by hroberts** [comment]
rt seems to work fine now.

**Comment by dsjen** [comment]
Amazing--thank you!
